## Figure 1
##
## by Artem Sokolov

source( "../results.R" )
source( "../plot.R" )

## Pre-defined index over results on previous AMP-AD gene sets
## Generated by the following code:
##   synResults() %>% filter( Type == "stats", Dataset != "MAYO" ) %>%
##     unnest() %>% filter( grepl("prev", fileName) ) %>%
##     select( -Type, -fileName ) %>% rename( id = fileId ) %>% dput()
indexPrev <- function()
{
    structure(list(Dataset = c("ROSMAP", "ROSMAP", "ROSMAP", "MSBB", 
                               "MSBB", "MSBB", "MSBB", "MSBB", "MSBB", "MSBB", "MSBB", "MSBB", 
                               "MSBB", "MSBB", "MSBB"),
                   Region = c("DLPFC", "DLPFC", "DLPFC", 
                              "BM10", "BM10", "BM10", "BM22", "BM22", "BM22", "BM36", "BM36", 
                              "BM36", "BM44", "BM44", "BM44"),
                   Task = c("AB", "AC", "BC", "AB", 
                            "AC", "BC", "AB", "AC", "BC", "AB", "AC", "BC", "AB", "AC", "BC"),
                   id = c("syn19036598", "syn19036646", "syn19036628", "syn19036634", 
                          "syn19036641", "syn19036584", "syn19036605", "syn19036577", "syn19036615", 
                          "syn19036659", "syn19036651", "syn19036595", "syn19036590", "syn19036624", 
                          "syn19036611")),
              row.names = c(NA, -15L), class = c("tbl_df", "tbl", "data.frame"))
}

panelC <- function()
{
    library( ggridges )
    
    ## Load all results associated with previous AMP-AD gene sets
    ## Isolate the slice of interest
    ## Tweak some names by hand
    X <- indexPrev() %>% mutate( Results = map(id, syn_csv) ) %>%
        select(-id) %>% retag() %>% unnest() %>% filter( Task == "A-vs-C" ) %>%
        select(-Task, -intersect, -adjusted_p, Size=n_genes) %>%
        arrange( p_value, desc(AUC) ) %>% group_by(id) %>% slice(1) %>% ungroup() %>%
        mutate_at("Size", ~round(./10)*10) %>%
        mutate_at("id", str_split, "-") %>%
        mutate_at("id", map_chr, ~str_c(.x[1]," (",.x[2],")") )

    ## Get the matching background
    XX <- indexBackground() %>% filter( Dataset != "MAYO", Task == "AC" ) %>% bkFromIndex() %>%
        unnest() %>% nest( AUC, .key="BK" ) %>% retag() %>% select( -Task ) %>% inner_join(X, .) %>%
        mutate( Name = glue::glue("{id}\n{description}"),
               Label = glue::glue("p={p_value}") ) %>%
        select( -id, -description ) %>%
        arrange( AUC ) %>% mutate_at( "Name", as_factor )
    BK <- XX %>% select( Name, Dataset, BK ) %>% unnest()

    ## Generate the ridge plots
    ggplot( BK, aes(x=AUC, y=Name, fill=Dataset) ) +
        theme_ridges(center_axis_labels=TRUE) +
        geom_density_ridges2(scale=1.25, size=1, alpha=0.5) +
        geom_segment( aes(x=AUC, xend=AUC, y=as.numeric(Name), yend=as.numeric(Name)+0.9),
                     data=XX, color="black", lwd=2 ) +
        geom_text( aes(y=as.numeric(Name)+0.75, label=Label, hjust=0),
                  x=0.87, hjust=0, data=XX, fontface="bold", size=4 ) +
        scale_y_discrete( name=NULL ) + coord_cartesian(clip="off") +
        scale_fill_manual( values=dsPal(), guide=FALSE ) 
    ##        theme( axis.text=etxt(12), axis.title=etxt(14) )
}

Fig1 <- function()
{
    ## Identify individual panels
    pA <- pdfGrob("syn20506948")
    pB <- pdfGrob("syn20506949")
    pC <- panelC()

    ## Put everything together
    fAB <- cowplot::plot_grid( NULL, pA, NULL, pB, ncol=2, labels=c("A","","B",""),
                              rel_widths=c(0.02,1), rel_heights=c(1,0.8), label_size=24 )
    ff <- cowplot::plot_grid( fAB, NULL, pC, nrow=1, labels=c("","C",""),
                             rel_widths=c(1.5,0.02,1), label_size=24 )
    
    cowplot::ggsave( str_c("Fig1-", Sys.Date(), ".pdf"), ff, width=14, height=7 )
}
